from flask.ext.wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import Required

class ReusableForm(Form):
    A1 = IntegerField([validators.Length(min=0, max=1)])



class BoardForm(Form):
    A1 = IntegerField([validators.Length(min=0, max=1)])
    A2 = IntegerField([validators.Length(min=0, max=1)])
    A3 = IntegerField([validators.Length(min=0, max=1)])
    A4 = IntegerField([validators.Length(min=0, max=1)])
    A5 = IntegerField([validators.Length(min=0, max=1)])
    A6 = IntegerField([validators.Length(min=0, max=1)])
    A7 = IntegerField([validators.Length(min=0, max=1)])
    A8 = IntegerField([validators.Length(min=0, max=1)])
    A9 = IntegerField([validators.Length(min=0, max=1)])

    B1 = IntegerField([validators.Length(min=0, max=1)])
    B2 = IntegerField([validators.Length(min=0, max=1)])
    B3 = IntegerField([validators.Length(min=0, max=1)])
    B4 = IntegerField([validators.Length(min=0, max=1)])
    B5 = IntegerField([validators.Length(min=0, max=1)])
    B6 = IntegerField([validators.Length(min=0, max=1)])
    B7 = IntegerField([validators.Length(min=0, max=1)])
    B8 = IntegerField([validators.Length(min=0, max=1)])
    B9 = IntegerField([validators.Length(min=0, max=1)])

    C1 = IntegerField([validators.Length(min=0, max=1)])
    C2 = IntegerField([validators.Length(min=0, max=1)])
    C3 = IntegerField([validators.Length(min=0, max=1)])
    C4 = IntegerField([validators.Length(min=0, max=1)])
    C5 = IntegerField([validators.Length(min=0, max=1)])
    C6 = IntegerField([validators.Length(min=0, max=1)])
    C7 = IntegerField([validators.Length(min=0, max=1)])
    C8 = IntegerField([validators.Length(min=0, max=1)])
    C9 = IntegerField([validators.Length(min=0, max=1)])

    D1 = IntegerField([validators.Length(min=0, max=1)])
    D2 = IntegerField([validators.Length(min=0, max=1)])
    D3 = IntegerField([validators.Length(min=0, max=1)])
    D4 = IntegerField([validators.Length(min=0, max=1)])
    D5 = IntegerField([validators.Length(min=0, max=1)])
    D6 = IntegerField([validators.Length(min=0, max=1)])
    D7 = IntegerField([validators.Length(min=0, max=1)])
    D8 = IntegerField([validators.Length(min=0, max=1)])
    D9 = IntegerField([validators.Length(min=0, max=1)])

    E1 = IntegerField([validators.Length(min=0, max=1)])
    E2 = IntegerField([validators.Length(min=0, max=1)])
    E3 = IntegerField([validators.Length(min=0, max=1)])
    E4 = IntegerField([validators.Length(min=0, max=1)])
    E5 = IntegerField([validators.Length(min=0, max=1)])
    E6 = IntegerField([validators.Length(min=0, max=1)])
    E7 = IntegerField([validators.Length(min=0, max=1)])
    E8 = IntegerField([validators.Length(min=0, max=1)])
    E9 = IntegerField([validators.Length(min=0, max=1)])

    F1 = IntegerField([validators.Length(min=0, max=1)])
    F2 = IntegerField([validators.Length(min=0, max=1)])
    F3 = IntegerField([validators.Length(min=0, max=1)])
    F4 = IntegerField([validators.Length(min=0, max=1)])
    F5 = IntegerField([validators.Length(min=0, max=1)])
    F6 = IntegerField([validators.Length(min=0, max=1)])
    F7 = IntegerField([validators.Length(min=0, max=1)])
    F8 = IntegerField([validators.Length(min=0, max=1)])
    F9 = IntegerField([validators.Length(min=0, max=1)])

    G1 = IntegerField([validators.Length(min=0, max=1)])
    G2 = IntegerField([validators.Length(min=0, max=1)])
    G3 = IntegerField([validators.Length(min=0, max=1)])
    G4 = IntegerField([validators.Length(min=0, max=1)])
    G5 = IntegerField([validators.Length(min=0, max=1)])
    G6 = IntegerField([validators.Length(min=0, max=1)])
    G7 = IntegerField([validators.Length(min=0, max=1)])
    G8 = IntegerField([validators.Length(min=0, max=1)])
    G9 = IntegerField([validators.Length(min=0, max=1)])

    H1 = IntegerField([validators.Length(min=0, max=1)])
    H2 = IntegerField([validators.Length(min=0, max=1)])
    H3 = IntegerField([validators.Length(min=0, max=1)])
    H4 = IntegerField([validators.Length(min=0, max=1)])
    H5 = IntegerField([validators.Length(min=0, max=1)])
    H6 = IntegerField([validators.Length(min=0, max=1)])
    H7 = IntegerField([validators.Length(min=0, max=1)])
    H8 = IntegerField([validators.Length(min=0, max=1)])
    H9 = IntegerField([validators.Length(min=0, max=1)])

    I1 = IntegerField([validators.Length(min=0, max=1)])
    I2 = IntegerField([validators.Length(min=0, max=1)])
    I3 = IntegerField([validators.Length(min=0, max=1)])
    I4 = IntegerField([validators.Length(min=0, max=1)])
    I5 = IntegerField([validators.Length(min=0, max=1)])
    I6 = IntegerField([validators.Length(min=0, max=1)])
    I7 = IntegerField([validators.Length(min=0, max=1)])
    I8 = IntegerField([validators.Length(min=0, max=1)])
    I9 = IntegerField([validators.Length(min=0, max=1)])
